version: '3'

services:
  places:
    image: ${PLACES_IMAGE}
    platform: linux/amd64
    ports:
      - "80:80"
    depends_on:
      - db_places
    environment:
      DB_HOST: db_places
      DB_PORT: 5432
      DB_NAME: your_database_name
      DB_USER: your_database_user
      DB_PASSWORD: your_database_password
    pull_policy: always 

  db_places:
    image: postgres:latest
    platform: linux/amd64
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    volumes:
      - ./places-dataset:/docker-entrypoint-initdb.d
    pull_policy: always 

  frontend:
    image: ${FRONTEND_IMAGE}
    platform: linux/amd64
    ports:
      - "8080:80"
    depends_on:
      - places
    environment:
      # WEB_SERVICE_HOST: places
      # WEB_SERVICE_PORT: 80
      PLACES_API_URL: http://places:80
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
    pull_policy: always 

volumes:
  postgres_data:
