name: prod-pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u lisachen0112 --password-stdin

      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ghcr.io/lisachen0112/accessable-maps-frontend:dev --push .